### ISSUE TITLE
Request to try out the rough version

### ISSUE THREAD

**Issue by tobylin19** [wouterkool/dpdp#2]
Hey there, thanks for the open source code! You mentioned in the other issue that you are still cleaning up the code. It will be great if you can share with me the rough version that you have. I am currently working on TSP for my final year project.

Also, may I know when will the clean version of the code be released? Thanks a lot!

**Comment by wouterkool** [comment]
Hi tobylin19,

Please reach out to me by e-mail (see the paper) and I'll give you the code which should be usable (but still some rough edges). I expect to have the code fully ready, verified and public in about 1-2 weeks.

**Comment by wouterkool** [comment]
Hi @tobylin19,

The code is now available! Please give it a try and let me know if you find any issue!
