### ISSUE TITLE
Customizing the start city

### ISSUE THREAD

**Issue by legohyl** [wouterkool/dpdp#3]
Hi Wouter, I noticed in your code that you don't support other starting points. I've been trying to get your DPDP search to work with my algorithm, but my algorithm has a specially crafted start point. Even after fixing this to node 0 and adding in an arbitrary coordinate, the code fails to run because you have quite a few points of checking to ensure that the cost matrix sums and the coordinate calculations don't deviate. 

Do you have any suggestions as how to "skip" the first city and not include it in the solution? I can't seem to be a good place to add this into the code.

**Comment by wouterkool** [comment]
Closing because you managed to solve this as discussed via e-mail. Solution is to include a dummy start city with a distance of 0 to all nodes, which needs to hack into some check functions to make it work.
